version: 2

jobs:
  build:
    working_directory: ~/source-data
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-bundle-{{ .Branch }}-
      - restore_cache:
          keys:
            - v1-cache
      - run:
          name: Dependency
          command: |
            gem install --no-document bundler
            bundle install --jobs=8 --deployment --path=vendor
      - save_cache:
          key: v1-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/source-data/.bundle
            - ~/source-data/vendor/bundle
      - run:
          name: Restore cache of archive
          command: |
            if [ -f cache/src.zip ]; then mv cache/src.zip data/src.zip; fi
            ./bin/zengin download
            mkdir -p cache
            cp data/src.zip cache/src.zip
      - save_cache:
          key: v1-cache
          paths:
            - ~/source-data/cache
      - run:
          name: Update archive
          command: ./bin/zengin update
      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then ./bin/zengin ci; fi
